### ISSUE TITLE
When manually triggering build, do not default builtin params to literal string $PARAM

### ISSUE THREAD

**Issue by johnathanhebert** [KyleLNicholls/parameterized-builds#120]
If you configure the hook to pass along a builtin param like $PRID, then manually triggering the job will use the correct value for $BRANCH, but other param values are given the literal string equal their identifier, like "$PRID".

Can you make it default to empty string instead? See example below -- I would expect $PRID in the screenshot to be empty string instead when manually triggering the build.

![image](https://user-images.githubusercontent.com/508820/37860931-97eae126-2efd-11e8-9db4-255794801c7d.png)

**Comment by a-hacker** [comment]
Hi @johnathanhebert. As you mentioned, sometimes certain parameters cannot be populated because they require a specific context to exist. In this case the $PRID needs to be triggered from a PR-related event or a manual build on the pull requests page. When those parameters aren't populated, they aren't added to the `BitbucketVariables` object which is really just a wrapper around a map from the param name to the actual value. Therefore, the param name ends up sticking around in your case.

We could update this logic so that all variables are populated with a default of an empty string but this would cause a change in expected behaviour for all our users which I'd rather not do unless there's a real issue with the current approach. Luckily, there are a few workarounds that might work for you:

1. If the only issue is with a manual build, then you can either perform a manual trigger from a PR page; or
2. when you trigger a manual build, simly edit the PR_ID field so that it is empty.
3. If you also have other non-PR triggers set for the job. You can create two separate items in the job triggers for the repo that point to the same job. The first only triggers on PR triggers and has `PR_ID=$PRID` in the build parameters. The second is on the non-PR triggers and has `PR_ID=` in the build parameters or doesn't have `PR_ID` in the build params at all to pick up the jenkins default.

I hope this provides a suitable compromise to your issue but at this time I do not plan on updating the default value for unpopulated params.
