### ISSUE TITLE
Unable to use with self-signed certificate

### ISSUE THREAD

**Issue by James-Newman** [KyleLNicholls/parameterized-builds#125]
I have an internal Jenkins using a self-signed certificate.

Using the parameterized-builds addon results in a particularly obscure error when attempting to use HTTPS.

![screen shot 2018-04-09 at 15 30 29](https://user-images.githubusercontent.com/10025570/38504360-643b4c78-3c0c-11e8-99c3-9817f758123d.png)

When using HTTP this issue is not present and the connection test is successful.

![screen shot 2018-04-09 at 15 32 57](https://user-images.githubusercontent.com/10025570/38504375-6d79b414-3c0c-11e8-9c88-d91824ad922a.png)

Adding the public certificate to the bitbucket java keystore does not appear to resolve this issue.

Is it possible to use the plugin with a Jenkins instance using a self-signed certificate?  If not currently, is it possible to include an option to disable certificate validation (along with a suitable warning regarding security risks)?

**Comment by James-Newman** [comment]
I should point out that the web interface is accessible on HTTPS, if that wasn't clear from the original submission.

**Comment by AndreyB22** [comment]
Same issue here. Doesn't work with self-signed SSL cert.
Used keytool to accept cert for BitBucket server but still no luck

**Comment by AndreyB22** [comment]
Okay, after couple of hours of research and analysis I finally solved the issue:

Let say you already have certificate for jenkins installed and have a file called jenkins.cer

Example in brackets
1. Go to your bitbucket jre installation folder and see which certs files you have (cd /opt/atlassian/bitbucket/4.14.4/jre/lib/security/)
There should be file called cacerts and there may also be jssecacerts
If you have jssecacerts use it bellow, otherwise use cacerts
2. Copy jenkins.cer to your bitbucket vm somewhere (/var/jenkins.cer)
3. Go to your bitbucket jre installation folder (cd /opt/atlassian/bitbucket/4.14.4/jre/)
4. Run keytool utility
(bin/keytool -import -file /var/jenkins.cer -alias <your jenkins url> -keystore /opt/atlassian/bitbucket/4.14.0/jre/lib/security/jssecacerts)
5. Restart BitBucket server

After that Self-signed certificate should work and parameterized-builds plugin should be able to connect and trigger jobs on your jenkins

**Comment by a-hacker** [comment]
@AndreyB22, thanks for figuring this out!

I'd like to add this to our documentation so that this knowledge does not get lost over time. I'll probably have some time this weekend to do a write-up. When I'm done, would you mind reviewing it to make sure it is accurate?

 Alternatively, if you have some spare time our wiki is publicly editable so you are free to write up a page yourself. I understand if writing documentation doesn't sound very appealing though. :laughing:

**Comment by AndreyB22** [comment]
@a-hacker Sure, I can review and adjust the wiki page :) I'm new to github so could you please create it first?

**Comment by a-hacker** [comment]
Sorry it took so long. I totally forgot about this :pensive:. I've added a new [wiki page](https://github.com/KyleLNicholls/parameterized-builds/wiki/Common-Questions) for user faqs which includes this issue and instructions on how to solve
