### ISSUE TITLE
When Jenkins project has a dot in the name, it can't be found

### ISSUE THREAD

**Issue by thestonehead** [KyleLNicholls/parameterized-builds#126]
All my projects follow One.Two.Three convention of naming, using a dot "." as a separator.
When I trigger a manual build, an error "Job was not found" pops up. It doesn't happen when there are no dots in the jenkins project name.

**Comment by a-hacker** [comment]
Hi @thestonehead. I am able to trigger jobs titled `job.name` and `job.name.name` both with and without parameters. I am using bitbucket version 5.4.0 and the latest version of this plugin (3.2.3) on jenkins lts version 2.60.3. 

I am going to close this issue since I cannot replicate the problem given the information provided. If you are able to provide more info that will allow me to replicate the problem, please re-open this issue and I will take another look into it.
