### ISSUE TITLE
Push new branch + commit doesn't run push event trigger alone

### ISSUE THREAD

**Issue by bighux** [KyleLNicholls/parameterized-builds#147]
We are using Bitbucket 5.5.0 & Parameterized-build 3.2.1 & jenkins 2.19.4

I have configured plugin with following options 
![image](https://user-images.githubusercontent.com/13555818/44591941-54513380-a7bf-11e8-847e-247525eee6b5.png)

I want only source code modification events in my jenkins job, I thought as Push Event was sufficient but with following sequence plugin doesn't run any job.

Sequence :

1- checkout git repository from bitbucket
2- create new branch in local (without push)
3- edit a file and commit on new branch (without push)
4- push on bitbucket repository (branch + commit)

Expected : Parameterized-build starts my job because I push new code
Current result : there is no job run

Push a code without new branch starts my job as wanted.

I have tested to enable event "Ref Created" in plugin and the job starts correctly with previous sequence.

I think it's a bug but may be the behavior is normal and documentation should be improved.

**Comment by a-hacker** [comment]
Hi @bighux. It is true that when a new branch is pushed it will not trigger a Push Event, only a Ref Created Event. This is due to Bitbucket considering a new branch to be an addition and not an update. 

We could allow for a new branch with commits to trigger as both a Push Event and a Ref Created Event. However, this would result in double triggers for users enabling both and could break expected functionality for other users. Therefore, I would not want to do this.

I will update our documentation to explicitly describe this behavior as it is not very intuitive. Another feature that could be added is a new "Bitbucket Variable" called PREVIOUS_COMMIT or something similar. This variable would be the commit hash for the commit prior to the ref change. This would allow you to check that the latest commit (the COMMIT variable) differs from the prior commit before doing any work in your job. If you would be interested in this, I will create a new issue for it. However, it will not be very high on my list of priorities and I will likely give it a "Good First Issue" tag.

**Comment by a-hacker** [comment]
The readme has been updated to be more clear on push functionality.
