### ISSUE TITLE
Enhancement Request : Add ability to configure Jenkins Server Per Repository

### ISSUE THREAD

**Issue by pduggishetti** [KyleLNicholls/parameterized-builds#164]
Currently  Jenkins configuration is supported 
- Per server instance (Gloablly) 
![image](https://user-images.githubusercontent.com/44791710/48037028-89fb8c80-e11f-11e8-88ba-31f3b98af475.png)

- Per Project - 
![image](https://user-images.githubusercontent.com/44791710/48036993-72bc9f00-e11f-11e8-86da-7d5301b774fb.png)

I am requesting to see if it is possible to add the Options per Repository under the addons
![image](https://user-images.githubusercontent.com/44791710/48037053-b8796780-e11f-11e8-926e-c02675a04b79.png)

**Comment by a-hacker** [comment]
Hi @pduggishetti. Thank you for the enhancement request. This is a feature that is often requested and is very much on my backlog of things to do. 

Since there is already an open issue about this (#64). I will close this as a duplicate. I would encourage you to either make a comment there or just give the issue a thumbs up.

Although I do plan on getting to this issue eventually, I have a lot of other responsibilities as the maintainer of this plugin so feature development is slow from me. If you would be interested in working on this yourself, I would be happy to get you up to speed on setting up your environment and answering any questions about the code. [Our Gitter](https://gitter.im/parameterized-builds/Lobby) would be a good place to chat.
