### ISSUE TITLE
For manual build need to pass PRID,PRAUTHOR etc.,but those fields should be hidden or non-editable, or can be passed to jenkins by default

### ISSUE THREAD

**Issue by kdatta10** [KyleLNicholls/parameterized-builds#206]
For manual build need to pass PRID,PRAUTHOR etc.,but those fields should be hidden or non-editable, or can be passed to jenkins by default

**Comment by a-hacker** [comment]
Hi @kdatta10. Thanks for submitting this issue! Could you please add some more details about the motivation behind this request? As is, I'm not sure this is something we would want to implement.

**Comment by kdatta10** [comment]
PRID, PRAUTHOR, COMMITID etc. need to be known by jenkins instance. If we need to pass those parameters in manual build then user will have an option to edit it, and in our case we don't want user to edit those field, but we want our jenkins instance to know all those variables.

**Comment by a-hacker** [comment]
Got it. Rather than making certain fields uneditable based on the default values, I think we would want the each parameter to be configurable somehow. This would have the benefit of both being more versatile for users who want to lock down specific parameters while also allowing other users who would want to edit PRID, etc fields the ability to do so.

Making this sort of change would be a large undertaking that would require a major overhaul to the way we store job data though. At this point I don't think this change will happen any time soon. For that reason I am going to close this issue.

If this request is critical to your use case, I'd recommend cloning this repo and trying to implement the change yourself. I'd be willing to provide guidance on testing and the structure of the codebase if you'd like.
