### ISSUE TITLE
Add support for Jenkins' CSRF protection token

### ISSUE THREAD

**Issue by pprkut** [KyleLNicholls/parameterized-builds#26]
Jenkins has a security setting "Prevent Cross Site Request Forgery exploits." When enabled, every remote API request needs to send a CSRF protection token with the request (see [this wiki page](https://wiki.jenkins-ci.org/display/JENKINS/Remote+access+API) for slightly more details).

The plugin currently doesn't support this and thus requests are blocked. We'd rather not disable this setting (specifically since the wiki page mentions this setting *should* be enabled), so we'd appreciate if support for it could be added.

**Comment by McNetic** [comment]
I think, technically, this is a problem of Jenkins. CSRF protection is meant to protect apis used from web browsers, using traditional authentication.
Public APIs secured by token-based authentication should not require CSRF protection, as the token is required for every request, anyways. I'm trying to get that sorted out with Jenkins.

That said, the problem with Jenkins in this case comes down to two parts: Authentication with user token and authentication with project api token. The former could be implemented by parametrized-builds (in fact, I have the implementation near ready, but postponed it when I recognized the problem actually lies within Jenkins - I will provide it if you really want to go down that road). The latter can not authenticate with CSRF enabled, because it's not possible to authenticate with the project token at Jenkins' CSRF service, so you can't get a CSRF token.

**Comment by KyleLNicholls** [comment]
I spent a little while on this issue. I don't think it's possible with the way Jenkins handles CSRF

**Comment by McNetic** [comment]
As I already mentioned, it *is* in fact possible to obtain and use CSRF tokens when using user api tokens. I have that one working here. I just think the Jenkins CSRF implementation is wrong. The corresponding issue with Jenkins is https://issues.jenkins-ci.org/browse/JENKINS-22474.
