### ISSUE TITLE
It would be helpful to have a branch filter for `PR MERGED` trigger

### ISSUE THREAD

**Issue by randomcoder** [KyleLNicholls/parameterized-builds#38]
We have a job that published artefacts to a local artifactory server that normally would only run when the PR is merged into `develop`. As we are following a `git-flow` style workflow, we will have two `PR MERGED` events for the same released version when we merge the release branch with `master` and then back onto `develop`. This is causing the second publish build to fail as the atrefact is already published.

If we could configure the `PR MERGED` trigger with a branch filter, as with the `PUSH EVENT` trigger this could be avoided.

Many Thanks,

**Comment by theage** [comment]
We want to trigger a dev build on our `develop` branch whenever something is merged into it.
However, when we merge `develop` into `master`, no dev build should be triggered as there are no changes to `develop`. It looks like we cannot restrict the PR merge event to the destination branch.

**Comment by K-4U** [comment]
I'm going to have to +1 this. 
We actually have two sites that run on the same codebase. So when we merge from `develop` into `master`, we now have 4 builds being triggered.

**Comment by KyleLNicholls** [comment]
I've been putting this off for a while. I'm starting to see configuration bloat in the hook configuration and I'm not a fan of the direction it's heading.
This suggestion would need to add a new branch filter that filters based off the destination (of the merge) instead of the source like the existing filter does (only for REF CREATED, PUSH EVENT, REF DELETED though). We would probably need new source and destination filters otherwise it could be confusing with the existing branch filter.

**Comment by shawnburrington** [comment]
Agreed, this would be super helpful. The bloat concern is understandable, but the additional flexibility would provide another great selling point for the plugin. We have some consumers that are backing away from using BB-controlled hooks because this level of flexibility isn't provided yet (they're resorting to Jenkins polling/Jenkins-controlled filters). Being able to filter off the destination branch for PRM's would end that discussion entirely.

**Comment by KyleLNicholls** [comment]
release in v3.1.2
