### ISSUE TITLE
Support for Organization Folders

### ISSUE THREAD

**Issue by lindt** [KyleLNicholls/parameterized-builds#63]
it seems that if Organization Folders are used, the job cannot be triggered anymore.
The URL will not be `jenkins/job/foo`, but more like `jenkins/job/MY_FOLDER/job/foo`.
If configure the job-name as `MY_FOLDE/job/foo` then it finds the job, but still cannot trigger it, even if it then gets a `200`.

**Comment by a-hacker** [comment]
I was able to trigger the job using MY_FOLDER/job/foo as the job-name. May I ask what version of Jenkins and the Folder plugin you are using?

**Comment by lindt** [comment]
When I configure `MY_FOLDER/job/foo` then I get a yellow message "job was not found" in stash when I trigger a branch-build manually.
Maybe there is also a difference between a normal folder and a "folder" created by cloudbees-bitbucket-branch-source?

Jenkins: 2.32.3
Jenkins Plugins:
- ansicolor:0.5.0
- bitbucket:1.1.5
- build-timeout:1.18
- buildtriggerbadge:2.8
- **cloudbees-bitbucket-branch-source:2.1.2**
- docker-plugin:0.16.2
- email-ext:2.57.1
- embeddable-build-status:1.9
- git-client:2.3.0
- htmlpublisher:1.12
- modernstatus:1.2
- pipeline-stage-view:2.6
- stashNotifier:1.11.6
- timestamper:1.8.8
- workflow-aggregator:2.5
- ws-cleanup:0.32
- xvfb:1.1.3

Parameterized Builds Stash Plugin: v2.6.6

**Comment by ganievs** [comment]
Hi guys. I have same problem. My jenkins version is  2.46.2

**Comment by ganievs** [comment]
> MY_FOLDER/job/foo 
It's work when Build Token Root disabled
![screenshot 1](https://cloud.githubusercontent.com/assets/19270785/25717722/08e873b6-310c-11e7-88dc-27be37e9ee84.png)

**Comment by a-hacker** [comment]
Hey everyone, sorry for dropping communication here. I struggled to set up a test environment for this issue when it was first mentioned and then a lot of stuff came up. I'm willing to take another look at it though.

@ganievs, based on what you've mentioned, there may be an issue with the way the rest API interacts with the cloudbees-bitbucket-branch-source plugin. @lindt, if this issue is still relevant to you, could you confirm whether or not you were using the build token root plugin when the issue occurred?

**Comment by lindt** [comment]
@a-hacker: it is still relevant.

did a workaround. cause still cannot trigger builds. The workaround is to everytime rescan the whole project for each code change. it is not nice, but at least it works.

**Comment by a-hacker** [comment]
@lindt, Okay. I'm working on a branch to support multibranch pipelines which I believe we solve this problem for you. I've been posting in the open, referenced issue linked above. If you think that their requests match yours, I'd ask that you close this issue and help give some insight/support there. Since I'm not too familiar with this feature of Jenkins, I'm not sure how related these requests are or the best way to solve them. Thanks for your patience.

**Comment by a-hacker** [comment]
@lindt, version 3.2.0 should solve your issue. If it does not, please feel free to re-open this issue.

**Comment by cgredig** [comment]
Sorry for asking on this old issue - I have version 3.2.1 of this plugin running on Bitbucket 5.7.0 with Jenkins 2.107.1 and I can't get a job inside a folder to work. I tried folder/jobname and folder/job/jobname both with and without activated multibranch pipeline checkbox. The job is of type "Pipeline". What am I missing?

**Comment by Gi0rgi0s** [comment]
A little late here... I found that formatting the job name like this _Folder/job-name_  in Stash did the trick.

**Comment by mariafleetwood** [comment]
I am trying to use "Parameterized Builds for Jenkins" (in bitbucket) to trigger jenkins job which created in  folders.

I have 3.2.10 version of  "Parameterized Builds for Jenkins" with  2.121.3 version of Jenkins. 
"Build Token Root Plugin" disabled. 

When trigger build in Bitbucket for jobs with are located in folders and in subfolder.   I tested both cases, both does not work. I used 
folder/job  
folder/subfolder/job 

I got message "Job was not found". Triggering works fine for jobs which are not in folders.

**Comment by a-hacker** [comment]
@mariafleetwood, If you are just using the [regular folders](https://wiki.jenkins.io/display/JENKINS/CloudBees+Folders+Plugin) then you'll want to set your job name as _folder_/job/_job_. So if your jenkins folder name is "AuditJobs" and your jenkins job name is "AuditDatabaseSize" then you'd set the job name in the hook settings as "AuditJobs/job/AuditDatabaseSize".

The issue here was with [Multibranch Pipelines](https://jenkins.io/doc/book/pipeline/multibranch/) and [Organization Folders](https://wiki.jenkins.io/display/JENKINS/GitHub+Organization+Folder+Plugin) which behave differently. If you are trying to trigger jobs that are part of a multibranch pipeline, make sure you set the `Multibranch Pipeline` checkbox and then set the job name as the Organization Folder.

**Comment by mariafleetwood** [comment]
> @mariafleetwood, If you are just using the [regular folders](https://wiki.jenkins.io/display/JENKINS/CloudBees+Folders+Plugin) then you'll want to set your job name as _folder_/job/_job_. So if your jenkins folder name is "AuditJobs" and your jenkins job name is "AuditDatabaseSize" then you'd set the job name in the hook settings as "AuditJobs/job/AuditDatabaseSize".
> 
> The issue here was with [Multibranch Pipelines](https://jenkins.io/doc/book/pipeline/multibranch/) and [Organization Folders](https://wiki.jenkins.io/display/JENKINS/GitHub+Organization+Folder+Plugin) which behave differently. If you are trying to trigger jobs that are part of a multibranch pipeline, make sure you set the `Multibranch Pipeline` checkbox and then set the job name as the Organization Folder.

Thanks!  

I just found it works if you don't use name of the job as it shown in JOB_NAME variable but use job name how it shown in browser (it work for jobs in subfolders as well)

Job in subfolder
<Folder Name>/job/<Sub-Folder Name>/job/<Your Job Name>
