### ISSUE TITLE
bitbucket branch source plugin

### ISSUE THREAD

**Issue by Kollerb04** [KyleLNicholls/parameterized-builds#65]
I'm trying to use the plugin with multibranch pipeline, but jenkins log shows me errors that crumb is expected and that none was delivered. How should I configure both jenkins and bitbucket to make this work? 

And second - bitbucket branch source pipelines tend to use longer paths for a given job, is there a possibility to automate the plugin somehow? Because I see that I need to add the hook for every job, can I parameterize the job name or its path?

**Comment by a-hacker** [comment]
The crumb issue you mention is likely due to CSRF protection being enabled on your Jenkins instance and not the multibranch pipeline. This issue was also brought up recently and I'm working on a solution for it.

As for automating the plugin for job names, were you thinking about something like regex support for the job names so that multiple jobs could be triggered at once with the same parameters if the job name matches the regex? If so, there is no support for anything like that but would be an interesting feature in the future.

**Comment by psotona** [comment]
Hi, 
this plugin does what we really need - triggerring build with specified params but it does not work for me & multibranch jobs. Do you have some experience in this way - supporting multibranch pipeline builds?Maybe I am missing something.

I guess that the main problem is that if you want to trigger build in multibranch project you must use 
different URL which is in format:
/job/PROJECT_NAME/job/BRANCH_NAME/build

Instead of:
/job/PROJECT_NAME/build

So correct call should be:
curl -isk -u bitbucket:608143XXXXc098 -X POST http://host/jenkins/job/project/job/master/build

If I use this plugin I am getting 302 error in return for multibranch jobs. What do you think?

**Comment by a-hacker** [comment]
Hi @psotona, I don't believe your issue relates to the one brought up be @Kollerb04 originally. That was unrelated to the the multibranch plugin. Instead, it was an issue with CSRF protection but I left the issue open because of the second request mentioned in the original post. If you could check out Issue #93 and confirm if that is your issue, I would greatly appreciate it.

**Comment by a-hacker** [comment]
@Kollerb04, did the csrf protection update introduced in version 2.6.8 solve your first issue? If so, I'd like to close this issue. Also, your second request sounds like you may be using the multibranch pipeline job type. If this is true, I'm working on supporting that jenkins feature in the issue I linked in my previous comment. Any help there is welcome and encouraged.

**Comment by a-hacker** [comment]
@Kollerb04, I'm going to close this issue and assume that the CSRF protection update solved your issue. If that is not true, please re-open and I'll take another look into it.
