### ISSUE TITLE
Question rather than Issue

### ISSUE THREAD

**Issue by rbhadti94** [KyleLNicholls/parameterized-builds#80]
Hi,

We're currently in the process of setting this up. However on our Jenkins server we have jobs inside folders. So for example we have the URL:
https:/ourdomain/folder1/subfolder2/job1

So as the job name would we do:
```job name: folder1/subfolder2/job1```

as this seems to give a permissions error?

**Comment by a-hacker** [comment]
A permissions issue is likely due to the user id and authentication token being invalid or that user does not have permission to build the specified job. If the job name is invalid, the error message should say "Job was not found." Depending on what Jenkins plugin you are using for foldering, you may have additional issues with your job not actually triggering. See Issue #63.
