### ISSUE TITLE
would like to have $COMMIT point at merge commit for MERGE events

### ISSUE THREAD

**Issue by cvaliente** [KyleLNicholls/parameterized-builds#90]
I would like to trigger my builds whenever a PR is merged, and build the resulting version of the master branch. Unfortunately $COMMIT refers to the last commitid that was merged, and not necessary the actual state of the master branch after the merge. On the other hand, I don't want to just build the latest version of master, because if several prs are merged and queued up in jenkins, each job would just build the latest version, instead of the exact state of the repository after the merge.

So I would like to have a variable pointing at the latest commit id of the target branch after the merge has happened

**Comment by a-hacker** [comment]
If you want to trigger a build whenever there's a new commit on master, you can set up the trigger to use the `PUSH` trigger rather than the `PR MERGED` trigger. When a PR is merged, it will cause a push event to occur and so your job will build. Just make sure to set the `Monitored Paths` field to be the name of your master branch so pushing to other branches doesn't cause a build.

If this doesn't solve your problem then I can look into adding a new variable but I'm not sure that the new commit ID is actually obtainable. It would also require a bit of code rewrite to add this variable for only the PR Merged so I'm not sure it is worth doing at present.

**Comment by cvaliente** [comment]
That would solve the problem, yes. Though the PR MERGED trigger also provides the Pull Request Id variable, so I can send back a message to the PR and other notification systems when the build has finished successfully (or not).
I also had a look at the PullRequest Java object and am not so sure if one can indeed get the new commit ID.
I'm still hopeful though, my use case doesn't seem that exotic. :)

**Comment by cvaliente** [comment]
https://developer.atlassian.com/static/javadoc/bitbucket-server/4.5.0-rc2/api/reference/com/atlassian/bitbucket/pull/PullRequestMergeActivity.html#getCommit()

PullRequestMergeActivity.getCommit() exposes the merge commit, not sure if it is accessible that easy.

**Comment by cvaliente** [comment]
made a suggestion in
https://github.com/KyleLNicholls/parameterized-builds/pull/92
